name: Devlopment Environment CI

on:
  push:
    branches:
      - dev

jobs:
  lint_dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci --ignore-scripts
      - run: npm run lint

      - name: 🔨 Build Project
        run: npm run build

  deploy_dev:
    runs-on: ubuntu-latest
    needs: lint_dev

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm ci --ignore-scripts
          npm run clasp
          npm run push
